ingredients_list = [
    "all-purpose flour",
    "almond milk",
    "almonds",
    "apple cider vinegar",
    "apples",
    "applesauce",
    "apricots",
    "arborio rice",
    "artichoke hearts",
    "asparagus",
    "avocado",
    "baby spinach",
    "bacon",
    "baking powder",
    "baking soda",
    "balsamic vinegar",
    "banana",
    "barley",
    "basil",
    "bay leaves",
    "beans",
    "beef",
    "beets",
    "bell pepper",
    "black beans",
    "black pepper",
    "blueberries",
    "bok choy",
    "bread crumbs",
    "broccoli",
    "brown rice",
    "brown sugar",
    "brussels sprouts",
    "butter",
    "buttermilk",
    "cabbage",
    "canned corn",
    "canned tomatoes",
    "capers",
    "carrots",
    "cashews",
    "cauliflower",
    "cayenne pepper",
    "celery",
    "chia seeds",
    "chickpeas",
    "chicken",
    "chicken broth",
    "chili powder",
    "chocolate chips",
    "cilantro",
    "cinnamon",
    "cocoa powder",
    "coconut milk",
    "coconut oil",
    "corn",
    "cornmeal",
    "cottage cheese",
    "cucumber",
    "cumin",
    "dark chocolate",
    "dates",
    "dijon mustard",
    "dried cranberries",
    "eggplant",
    "eggs",
    "feta cheese",
    "flax seeds",
    "garlic",
    "ginger",
    "goat cheese",
    "granulated sugar",
    "green beans",
    "green onions",
    "ground beef",
    "ground turkey",
    "honey",
    "jalapeno",
    "kale",
    "leeks",
    "lemon",
    "lentils",
    "lime",
    "maple syrup",
    "mayonnaise",
    "milk",
    "mozzarella cheese",
    "mushrooms",
    "nutmeg",
    "oats",
    "olive oil",
    "onion",
    "orange",
    "oregano",
    "paprika",
    "parmesan cheese",
    "parsley",
    "peanut butter",
    "peas",
    "pecans",
    "pineapple",
    "pistachios",
    "potatoes",
    "quinoa",
    "raisins",
    "raspberries",
    "red pepper flakes",
    "red wine vinegar",
    "rice",
    "rice vinegar",
    "rosemary",
    "sage",
    "salmon",
    "scallions",
    "shallots",
    "shrimp",
    "sour cream",
    "soy sauce",
    "spinach",
    "squash",
    "strawberries",
    "sun-dried tomatoes",
    "sweet potatoes",
    "thyme",
    "tofu",
    "tomato paste",
    "tomatoes",
    "turmeric",
    "vanilla extract",
    "walnuts",
    "white wine vinegar",
    "whole wheat flour",
    "yogurt",
    "zucchini",
]
