import React, { useState, useEffect } from 'react';
import RecipeImage from './ReceipeImage';

import Recipe from '../models/recipe';
import User from '../models/user';
import axios from 'axios';

interface RecipeCardProps {
  recipe: Recipe;
  token: string;
}

const RecipeCard: React.FC<RecipeCardProps> = ({ recipe, token }) => {
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    async function fetchUser() {
      try {
        const response = await axios.get<User>(`/api/user/${recipe.author}`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        setUser(response.data);
      } catch (error) {
        console.error('Error fetching user:', error);
      }
    }

    fetchUser();
  }, [recipe.author, token]);

  return (
    <div className="bg-white rounded-lg shadow-md overflow-hidden">
      <div className="relative">
        <RecipeImage token={token} />
        <div className="absolute top-4 right-4 flex items-center space-x-2">
          <span className="text-gray-800">{user?.username}</span>
          <img src={user?.picture} alt={user?.username} className="w-8 h-8 rounded-full" />
        </div>
      </div>
      <div className="p-4">
        <h3 className="text-xl font-semibold text-gray-800 mb-2">{recipe.title}</h3>
        <div>
          <h4 className="text-lg font-semibold text-gray-700 mb-1">Ingredients</h4>
          <ul className="list-disc list-inside space-y-1">
            {recipe.ingredients.map((ingredient) => (
              <li className="text-gray-600" key={ingredient}>{ingredient}</li>
            ))}
          </ul>
        </div>
        <div>
          <h4 className="text-lg font-semibold text-gray-700 mb-1 mt-4">Directions</h4>
          <ol className="list-decimal list-inside space-y-1">
            {recipe.directions.map((direction, index) => (
              <li className="text-gray-600" key={index}>
                <strong>Step {index + 1}</strong>: {direction}
              </li>
            ))}
          </ol>
        </div>
      </div>
      <div className="px-4 py-2 bg-gray-100 border-t border-gray-200">
        {recipe.generatedByNLP ? (
          <span className="text-gray-600">Generated by AI</span>
        ) : (
          <span className="text-gray-600">Created by {user?.username}</span>
        )}
      </div>
    </div>
  );
};

export default RecipeCard;
